spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.147.19.88:3306/small_oms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.147.19.99:30044
  application:
    name: small-order
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


server:
  port: 9000