spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.147.19.99:30044
    alicloud:
      access-key: LTAI4FyGwUbN2bsbuPCNm1Dr
      secret-key: q0sE7PnXRqydS4tisyWKEXMHk3HYyH
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: small


  application:
    name: small-third-party

server:
  port: 30000


